// automatically generated by ida2asm, do not edit!

#pragma once


// ---------------------------------------------------------------------------

// this enum *must* be first, for menu script to work properly
// enum Sprites, mappedto_1
#define SPR_SMALL_ZERO 8
#define SPR_EDIT_TACTICS_SMALL_PL_WHITE_GUY 124
#define SPR_EDIT_TACTICS_SMALL_PL_RED_GUY 125
#define SPR_EDIT_TACTICS_SMALL_PL_BLACK_GUY 126
#define SPR_TACTICS_CURSOR_0 149
#define SPR_TACTICS_CURSOR_1 150
#define SPR_TACTICS_CURSOR_2 151
#define SPR_NOT_PLAYING_1_GAME 156
#define SPR_NOT_PLAYING_2_GAMES 157
#define SPR_NOT_PLAYING_3_GAMES 158
#define SPR_NOT_PLAYING_4_GAMES 159
#define SPR_NOT_PLAYING_UNKNOWN 160
#define SPR_NOT_PLAYING_WHOLE_SEASON 161
#define SPR_SMALL_1 162
#define SPR_SMALL_2 163
#define SPR_SMALL_3 164
#define SPR_SMALL_4 165
#define SPR_SMALL_5 166
#define SPR_SMALL_6 167
#define SPR_SMALL_7 168
#define SPR_SMALL_8 169
#define SPR_SMALL_9 170
#define SPR_SMALL_10 171
#define SPR_SMALL_11 172
#define SPR_EMPTY_01 181
#define SPR_EMPTY_02 182
#define SPR_SCROLL_ARROW_UP 183
#define SPR_SCROLL_ARROW_DOWN 184
#define SPR_PL_FACE_WHITE_GUY 186
#define SPR_PL_FACE_RED_GUY 187
#define SPR_PL_FACE_BLACK_GUY 188
#define SPR_EMPTY_03 189
#define SPR_BIG_SHIRT 190
#define SPR_BIG_SHORTS 191
#define SPR_BIG_SOCKS 192
#define SPR_EDIT_TEAMS_PRIMARY_SHIRT 193
#define SPR_EDIT_TEAMS_SHORTS 194
#define SPR_EDIT_TEAMS_SOCKS 195
#define SPR_EDIT_TEAMS_SECONDARY_SHIRT 196
#define SPR_EDIT_TEAMS_SHORTS_SECONDARY 197
#define SPR_EDIT_TEAMS_SECONDARY_SOCKS 198
#define SPR_PLAIN_SHIRT 199
#define SPR_COLORED_SLEEVES_SHIRT 200
#define SPR_VERTICAL_STRIPES_SHIRT 201
#define SPR_HORIZONTAL_STRIPES_SHIRT 202
#define SPR_CHECK_BIG 206
#define SPR_NOT_CHECK_BIG 207
#define SPR_CHECK_SMALL 208
#define SPR_NOT_CHECK_SMALL 209
#define SPR_LITTLE_PLAYER_VERT_STRIPES 210
#define SPR_LITTLE_PLAYER_NO_STRIPES 211
#define SPR_LITTLE_PLAYER_HOR_STRIPES 212
#define SPR_LITTLE_PLAYER_GOALIE 213
#define SPR_LITTLE_PLAYER_GENERIC 214
#define SPR_PREMIERE_DIVISION_WINNER 215
#define SPR_INVITATION_TOURNAMENT 216
#define SPR_CUP_WINNER 217
#define SPR_UNKNOWN_TROPHY 218
#define SPR_EUROPEAN_CHAMPIONS_CUP 219
#define SPR_CUP_WINNERS_CUP 220
#define SPR_UEFA_CUP 221
#define SPR_WORLD_CUP 222
#define SPR_EUROPEAN_CHAMPIONSHIP 223
#define SPR_PITCH_IN_PLAY_MATCH_MENU 225
#define SPR_TACTICS_PITCH 226
#define SPR_ADVERT_1_PART_1 227
#define SPR_ADVERT_1_PART_2 228
#define SPR_ADVERT_1_PART_3 229
#define SPR_ADVERT_1_PART_4 230
#define SPR_ADVERT_1_PART_5 231
#define SPR_ADVERT_1_PART_6 232
#define SPR_ADVERT_1_PART_7 233
#define SPR_ADVERT_1_PART_8 234
#define SPR_ADVERT_2_PART_1 235
#define SPR_ADVERT_2_PART_2 236
#define SPR_ADVERT_2_PART_3 237
#define SPR_ADVERT_2_PART_4 238
#define SPR_ADVERT_2_PART_5 239
#define SPR_ADVERT_2_PART_6 240
#define SPR_ADVERT_2_PART_7 241
#define SPR_ADVERT_2_PART_8 242
#define SPR_ADVERT_3_PART_1 243
#define SPR_ADVERT_3_PART_2 244
#define SPR_ADVERT_3_PART_3 245
#define SPR_ADVERT_3_PART_4 246
#define SPR_ADVERT_3_PART_5 247
#define SPR_ADVERT_3_PART_6 248
#define SPR_ADVERT_3_PART_7 249
#define SPR_ADVERT_3_PART_8 250
#define SPR_SQUARE_GRID_FOR_RESULT 252
#define SPR_RED_CARD_SMALL 253
#define SPR_YELLOW_CARD_SMALL 254
#define SPR_TEAM1_PLAYER_NAMES_START 255
#define SPR_TEAM2_PLAYER_NAMES_START 271
#define SPR_BIG_0 287
#define SPR_BIG_1 288
#define SPR_BIG_2 289
#define SPR_BIG_3 290
#define SPR_BIG_4 291
#define SPR_BIG_5 292
#define SPR_BIG_6 293
#define SPR_BIG_7 294
#define SPR_BIG_8 295
#define SPR_BIG_9 296
#define SPR_RESULT_BIG_0 297
#define SPR_RESULT_BIG_1 298
#define SPR_RESULT_BIG_2 299
#define SPR_RESULT_BIG_3 300
#define SPR_RESULT_BIG_4 301
#define SPR_RESULT_BIG_5 302
#define SPR_RESULT_BIG_6 303
#define SPR_RESULT_BIG_7 304
#define SPR_RESULT_BIG_8 305
#define SPR_RESULT_BIG_9 306
#define SPR_TEAM1_NAME 307
#define SPR_TEAM2_NAME 308
#define SPR_BIG_DASH 309
#define SPR_8_MINS 328
#define SPR_88_MINS 329
#define SPR_118_MINS 330
#define SPR_TIME_BIG_0 331
#define SPR_TIME_BIG_1 332
#define SPR_TIME_BIG_2 333
#define SPR_TIME_BIG_3 334
#define SPR_TIME_BIG_4 335
#define SPR_TIME_BIG_5 336
#define SPR_TIME_BIG_6 337
#define SPR_TIME_BIG_7 338
#define SPR_TIME_BIG_8 339
#define SPR_TIME_BIG_9 340
#define SPR_INJURED_PLAYER1_TOP_RIGHT_FRAME_0 411
#define SPR_INJURED_PLAYER1_TOP_RIGHT_FRAME_1 412
#define SPR_INJURED_PLAYER1_TOP_LEFT_FRAME_0 413
#define SPR_INJURED_PLAYER1_TOP_LEFT_FRAME_1 414
#define SPR_INJURED_PLAYER2_TOP_RIGHT_FRAME_0 714
#define SPR_INJURED_PLAYER2_TOP_RIGHT_FRAME_1 715
#define SPR_INJURED_PLAYER2_TOP_LEFT_FRAME_0 716
#define SPR_INJURED_PLAYER2_TOP_LEFT_FRAME_1 717
#define SPR_GOALIE1_CAUGHT_BALL_RIGHT 976
#define SPR_GOALIE1_CAUGHT_BALL_LEFT 978
#define SPR_GOALIE2_CAUGHT_BALL_RIGHT 1106
#define SPR_GOALIE2_CAUGHT_BALL_LEFT 1108
#define SPR_BALL1 1179
#define SPR_BALL2 1180
#define SPR_BALL3 1181
#define SPR_BALL4 1182
#define SPR_BALL_SHADOW 1183
#define SPR_CORNER_FLAG_FRAME_0 1184
#define SPR_CORNER_FLAG_FRAME_1 1185
#define SPR_CORNER_FLAG_FRAME_2 1186
#define SPR_CORNER_FLAG_FRAME_3 1187
#define SPR_PLAYER_MARK 1204
#define SPR_UPPER_GOAL_TOP 1205
#define SPR_LOWER_GOAL_BOTTOM 1206
#define SPR_SQUARE_GRID 1207
#define SPR_REPLAY_FRAME_00 1209
#define SPR_REPLAY_FRAME_01 1210
#define SPR_REPLAY_FRAME_02 1211
#define SPR_REPLAY_FRAME_03 1212
#define SPR_REPLAY_FRAME_04 1213
#define SPR_REPLAY_FRAME_05 1214
#define SPR_REPLAY_FRAME_06 1215
#define SPR_REPLAY_FRAME_07 1216
#define SPR_REPLAY_FRAME_08 1217
#define SPR_REPLAY_FRAME_09 1218
#define SPR_REPLAY_FRAME_10 1219
#define SPR_REPLAY_FRAME_11 1220
#define SPR_REPLAY_FRAME_12 1221
#define SPR_REPLAY_FRAME_13 1222
#define SPR_REPLAY_FRAME_14 1223
#define SPR_REPLAY_FRAME_15 1224
#define SPR_REPLAY_FRAME_16 1225
#define SPR_REPLAY_FRAME_17 1226
#define SPR_REPLAY_FRAME_18 1227
#define SPR_REPLAY_FRAME_19 1228
#define SPR_REPLAY_FRAME_20 1229
#define SPR_REPLAY_FRAME_21 1230
#define SPR_REPLAY_FRAME_22 1231
#define SPR_REPLAY_FRAME_23 1232
#define SPR_REPLAY_FRAME_24 1233
#define SPR_REPLAY_FRAME_25 1234
#define SPR_REPLAY_FRAME_26 1235
#define SPR_REPLAY_FRAME_27 1236
#define SPR_REPLAY_FRAME_28 1237
#define SPR_REPLAY_FRAME_29 1238
#define SPR_REPLAY_FRAME_30 1239
#define SPR_REPLAY_FRAME_31 1240
#define BIG_S_FRAME_00 1241
#define BIG_S_FRAME_01 1242
#define BIG_S_FRAME_02 1243
#define BIG_S_FRAME_03 1244
#define BIG_S_FRAME_04 1245
#define BIG_S_FRAME_05 1246
#define BIG_S_FRAME_06 1247
#define BIG_S_FRAME_07 1248
#define BIG_S_FRAME_08 1249
#define BIG_S_FRAME_09 1250
#define BIG_S_FRAME_10 1251
#define BIG_S_FRAME_11 1252
#define BIG_S_FRAME_12 1253
#define BIG_S_FRAME_13 1254
#define BIG_S_FRAME_14 1255
#define BIG_S_FRAME_15 1256
#define BIG_S_FRAME_16 1257
#define BIG_S_FRAME_17 1258
#define BIG_S_FRAME_18 1259
#define BIG_S_FRAME_19 1260
#define BIG_S_FRAME_20 1261
#define BIG_S_FRAME_21 1262
#define BIG_S_FRAME_22 1263
#define BIG_S_FRAME_23 1264
#define BIG_S_FRAME_24 1265
#define BIG_S_FRAME_25 1266
#define BIG_S_FRAME_26 1267
#define BIG_S_FRAME_27 1268
#define BIG_S_FRAME_28 1269
#define BIG_S_FRAME_29 1270
#define BIG_S_FRAME_30 1271
#define BIG_S_FRAME_31 1272
#define SPR_SELECT_SUBSTITUTE_ARROW 1284
#define SPR_SUBSTITUTES 1288
#define SPR_FORMATION 1289
#define SPR_RED_CROSS_INJURY 1290
#define SPR_RED_CARD 1291
#define SPR_YELLOW_CARD 1292
#define SPR_WHITE_GUY_FACE 1293
#define SPR_RED_GUY_FACE 1294
#define SPR_BLACK_GUY_FACE 1295
#define SPR_COACH1_SITTING_1 1296
#define SPR_COACH1_SITTING_2 1297
#define SPR_COACH1_SITTING_3 1298
#define SPR_COACH1_STANDING_1 1299
#define SPR_COACH1_STANDING_2 1300
#define SPR_COACH1_STANDING_3 1301
#define SPR_COACH2_SITTING_1 1303
#define SPR_COACH2_SITTING_2 1304
#define SPR_COACH2_SITTING_3 1305
#define SPR_COACH2_STANDING_1 1306
#define SPR_COACH2_STANDING_2 1307
#define SPR_COACH2_STANDING_3 1308
#define SPR_BENCH_SITTING_GOALIE_WHITE 1310
#define SPR_BENCH_SITTING_GOALIE_GINGER 1311
#define SPR_BENCH_SITTING_GOALIE_BLACK 1312
#define SPR_BENCH_PLAYER_SITTING_WHITE 1313
#define SPR_BENCH_PLAYER_SITTING_GINGER 1314
#define SPR_BENCH_PLAYER_SITTING_BLACK 1315
#define SPR_BENCH_STANDING_GOALIE_WHITE 1316
#define SPR_BENCH_STANDING_GOALIE_GINGER 1317
#define SPR_BENCH_STANDING_GOALIE_BLACK 1318
#define SPR_BENCH_STANDING_PLAYER_WHITE 1319
#define SPR_BENCH_STANDING_PLAYER_GINGER 1320
#define SPR_BENCH_STANDING_PLAYER_BLACK 1321
#define SPR_RESERVE_PLAYERS_SITTING1 1322

// ---------------------------------------------------------------------------

// enum Switches, mappedto_2
#define OFF 0
#define ON 1

// ---------------------------------------------------------------------------

// enum MrOrMsEnum, mappedto_3
#define MR 0
#define MS 1

// ---------------------------------------------------------------------------

// enum TeamTypes, mappedto_4
#define NATIONAL_TEAMS 0
#define CLUB_TEAMS 1
#define ORIGINAL_CUSTOM_TEAMS 2
#define EDITED_CUSTOM_TEAMS 3
#define NONE 0x0FFFFFFFF

// ---------------------------------------------------------------------------

// enum GameTypes, mappedto_5
#define GAME_TYPE_NO_GAME 0
#define GAME_TYPE_DIY_COMPETITION 1
#define GAME_TYPE_PRESET_COMPETITION 2
#define GAME_TYPE_SEASON 3
#define GAME_TYPE_CAREER 4

// ---------------------------------------------------------------------------

// enum Seasons, mappedto_6
#define SEASON_JAN 0
#define SEASON_FEB 1
#define SEASON_MAR 2
#define SEASON_APR 3
#define SEASON_MAY 4
#define SEASON_JUN 5
#define SEASON_JUL 6
#define SEASON_AUG 7
#define SEASON_SEP 8
#define SEASON_OCT 9
#define SEASON_NOV 0x0A
#define SEASON_DEC 0x0B

// ---------------------------------------------------------------------------

// enum PitchTypeEnum, copyof_7
#define FROZEN 0
#define MUDDY 1
#define WET 2
#define SOFT 3
#define NORMAL 4
#define DRY 5
#define HARD 6
#define SEASONAL 0x0FFFE
#define RANDOM 0x0FFFF

// ---------------------------------------------------------------------------

// enum GameLengthEnum, mappedto_8
#define LENGTH_3_MINS 0
#define LENGTH_5_MINS 1
#define LENGTH_7_MINS 2
#define LENGTH_10_MINS 3

// ---------------------------------------------------------------------------

// enum Positions, mappedto_10
#define POS_GOALKEEPER 0
#define POS_RIGHT_BACK 1
#define POS_LEFT_BACK 2
#define POS_DEFENDER 3
#define POS_RIGHT_WING 4
#define POS_LEFT_WING 5
#define POS_MIDFIELDER 6
#define POS_ATTACKER 7

// ---------------------------------------------------------------------------

// enum TacticsEnum, mappedto_11
#define TACTIC_DEFAULT 0
#define TACTIC_5_4_1 1
#define TACTIC_4_5_1 2
#define TACTIC_5_3_2 3
#define TACTIC_3_5_2 4
#define TACTIC_4_3_3 5
#define TACTIC_4_2_4 6
#define TACTIC_3_4_3 7
#define TACTIC_SWEEP 8
#define TACTIC_5_2_3 9
#define TACTIC_ATTACK 10
#define TACTIC_DEFEND 11
#define TACTIC_USER_A 12
#define TACTIC_USER_B 13
#define TACTIC_USER_C 14
#define TACTIC_USER_D 15
#define TACTIC_USER_E 16
#define TACTIC_USER_F 17
#define TACTIC_IMPORTED 1000

// ---------------------------------------------------------------------------

// enum ClubMessages, mappedto_12
#define CLUB_UNWILLING_TO_PURCHASE_PLAYERS 1
#define TOO_LARGE_SQUAD 2
#define NO_MORE_TIME_TO_NEGOTIATE 3
#define NO_MORE_PLAYER_SALES 4
#define BANK_BALANCE_OVERDRAFT 5
#define OVERDRAFT_LAST_WARNING 6
#define CLEAR_OVERDRAFT_IMMEDIEATELY 7
#define YOURE_SACKED 8
#define IMPROVE_LEAGUE_POSITION 9
#define IMPROVE_LEAGUE_POSITION_SOON 10
#define THREE_MORE_MATCHES_TO_IMPROVE_TEAM 11
#define YOURE_SACKED_2 12
#define WELL_DONE_EXCELLENT_JOB 13
#define GOOD_SEASON_ALL_PLEASED 14
#define UP_AND_DOWN_SEASON 15
#define NOT_A_VERY_GOOD_SEASON 16
#define DISAPPOINTING_SEASON 17
#define THANKS_FOR_ALL_HELP 18
#define WELCOME_TO_OUR_CLUB 19
#define LAST_SEASON_BEFORE_RETIREMENT 20
#define WISH_YOU_EVERY_SUCCESS 21
#define ENJOY_LAST_SEASON 22
#define ENJOY_YOUR_RETIREMENT 23
#define TRIAL_PLAYER_LEFT_CLUB 24
#define RESERVE_PLAYER_LEFT_CLUB 25
#define PLAYER_JOINED_CLUB_ON_TRIAL 26
#define EXCELLENT_JOB_THIS_SEASON 27
#define GOOD_SEASON 28
#define UP_AND_DOWN_SEASON2 29
#define NOT_A_VERY_GOOD_SEASON2 30
#define VERY_DISSAPOINTING_SEASON 31
#define THANKS_FOR_ALL_YOUR_HELP 32
#define WELCOME_WE_LOOK_FORWARD 33
#define WELCOME_ENJOY_YOUR_LAST_SEASON 34
#define WISH_YOU_SUCESS 35
#define ENJOY_LAST_SEASON_BEFORE 36
#define WISH_YOU_BEST_AT_THE_END 37
#define WE_DIDNT_RENEW_YOUR_CONTRACT 38

// ---------------------------------------------------------------------------

// enum CountryNumbers, mappedto_13
#define CN_ALBANIA 0
#define CN_AUSTRIA 1
#define CN_BELGIUM 2
#define CN_BULGARIA 3
#define CN_CROATIA 4
#define CN_CYPRUS 5
#define CN_CZECH_REPUBLIC 6
#define CN_DENMARK 7
#define CN_ENGLAND 8
#define CN_ESTONIA 10
#define CN_FAROE_ISLANDS 11
#define CN_FINLAND 12
#define CN_FRANCE 13
#define CN_GERMANY 14
#define CN_GREECE 15
#define CN_HUNGARY 16
#define CN_ICELAND 17
#define CN_REPUBLIC_IRELAND 18
#define CN_ISRAEL 19
#define CN_ITALY 20
#define CN_LATVIA 21
#define CN_LITHUANIA 22
#define CN_LUXEMBOURG 23
#define CN_MALTA 24
#define CN_HOLLAND 25
#define CN_NORTHERN_IRELAND 26
#define CN_NORWAY 27
#define CN_POLAND 28
#define CN_PORTUGAL 29
#define CN_ROMANIA 30
#define CN_RUSSIA 31
#define CN_SAN_MARINO 32
#define CN_SCOTLAND 33
#define CN_SLOVENIA 34
#define CN_SPAIN 35
#define CN_SWEDEN 36
#define CN_SWITZERLAND 37
#define CN_TURKEY 38
#define CN_UKRAINE 39
#define CN_WALES 40
#define CN_YUGOSLAVIA 41
#define CN_ALGERIA 42
#define CN_ARGENTINA 43
#define CN_AUSTRALIA 44
#define CN_BOLIVIA 45
#define CN_BRAZIL 46
#define CN_CHILE 48
#define CN_COLOMBIA 49
#define CN_ECUADOR 50
#define CN_EL_SALVADOR 51
#define CN_JAPAN 55
#define CN_MEXICO 60
#define CN_NEW_ZEALAND 62
#define CN_PARAGUAY 64
#define CN_PERU 65
#define CN_SURINAM 66
#define CN_TAIWAN 67
#define CN_SOUTH_AFRICA 69
#define CN_URUGUAY 71
#define CN_USA 73
#define CN_INDIA 75
#define CN_BELARUS 76
#define CN_VENEZUELA 77
#define CN_SLOVAKIA 78
#define CN_GHANA 79
#define CN_EUROPE 80
#define CN_AFRICA 81
#define CN_SOUTH_AMERICA 82
#define CN_NORTH_AMERICA 83
#define CN_ASIA 84
#define CN_OCEANIA 85

// ---------------------------------------------------------------------------

// enum TeamControls, mappedto_14
#define TEAM_NOT_SELECTED 0
#define TEAM_COMPUTER 1
#define TEAM_PLAYER_COACH 2
#define TEAM_COACH 3

// ---------------------------------------------------------------------------

// enum ShirtTypes, mappedto_15
#define SHIRT_ORDINARY 0
#define SHIRT_COLORED_SLEEVES 1
#define SHIRT_VERTICAL_STRIPES 2
#define SHIRT_HORIZONTAL_STRIPES 3

// ---------------------------------------------------------------------------

// enum MenuEntryType1, mappedto_16
#define NO_BACKGROUND 0
#define ENTRY_FUNC1 1
#define ENTRY_FRAME_AND_BACK_COLOR 2
#define ENTRY_SPRITE1 3

// ---------------------------------------------------------------------------

// enum MenuEntryType2, mappedto_17
#define NO_FOREGROUND 0
#define ENTRY_FUNC2 1
#define ENTRY_STRING 2
#define ENTRY_SPRITE2 3
#define ENTRY_STRING_TABLE 4
#define ENTRY_MULTI_LINE_TEXT 5
#define ENTRY_NUMBER 6
#define ENTRY_SPRITE_COPY 7

// ---------------------------------------------------------------------------

// enum MenuEntryColors, mappedto_18
#define PINK_TO_BROWN_0 0
#define PINK_TO_BROWN_1 1
#define PINK_TO_BROWN_2 2
#define BLUE_TO_BLACK_3 3
#define ORANGE_TO_BROWN_4 4
#define ORANGE_TO_BROWN_5 5
#define ORANGE_TO_BROWN_6 6
#define PINK_TO_BROWN_7 7
#define BLUE_TO_BLACK_8 8
#define PINK_TO_BROWN_9 9
#define RED_10 0x0A
#define BLUE_TO_PURPLE_11 0x0B
#define ORANGE_TO_BROWN_12 0x0C
#define BRIGHT_BLUE_TO_BLUE_13 0x0D
#define YELLOW_GREEN_BLACK_14 0x0E
#define YELLOW_GREEN_BLACK_15 0x0F

// ---------------------------------------------------------------------------

// enum ScanCodes, mappedto_19
#define KEY_F4 0x3E
#define KEY_F7 0x41
#define KEY_F8 0x42
#define KEY_F9 0x43
#define KEY_F10 0x44
#define KEY_PAGE_UP 0x49
#define KEY_PAGE_DOWN 0x51

// ---------------------------------------------------------------------------

// enum GameStates, mappedto_20
#define ST_PLAYERS_TO_INITIAL_POSITIONS 0
#define ST_GOAL_OUT_LEFT 1
#define ST_GOAL_OUT_RIGHT 2
#define ST_KEEPER_HOLDS_BALL 3
#define ST_CORNER_LEFT 4
#define ST_CORNER_RIGHT 5
#define ST_FREE_KICK_LEFT1 6
#define ST_FREE_KICK_LEFT2 7
#define ST_FREE_KICK_LEFT3 8
#define ST_FREE_KICK_CENTER 9
#define ST_FREE_KICK_RIGHT1 10
#define ST_FREE_KICK_RIGHT2 11
#define ST_FREE_KICK_RIGHT3 12
#define ST_FOUL 13
#define ST_PENALTY 14
#define ST_THROW_IN_FORWARD_RIGHT 15
#define ST_THROW_IN_CENTER_RIGHT 16
#define ST_THROW_IN_BACK_RIGHT 17
#define ST_THROW_IN_FORWARD_LEFT 18
#define ST_THROW_IN_CENTER_LEFT 19
#define ST_THROW_IN_BACK_LEFT 20
#define ST_STARTING_GAME 21
#define ST_CAMERA_GOING_TO_SHOWERS 22
#define ST_GOING_TO_HALFTIME 23
#define ST_PLAYERS_GOING_TO_SHOWER 24
#define ST_RESULT_ON_HALFTIME 25
#define ST_RESULT_AFTER_THE_GAME 26
#define ST_FIRST_EXTRA_STARTING 27
#define ST_FIRST_EXTRA_ENDED 28
#define ST_FIRST_HALF_ENDED 29
#define ST_GAME_ENDED 30
#define ST_PENALTIES 31
#define ST_GAME_IN_PROGRESS 100
#define ST_STOPPED 101
#define ST_WAITING_ON_PLAYER 102

// ---------------------------------------------------------------------------

// enum PlayerStates, mappedto_21
#define PL_NORMAL 0
#define PL_TACKLING 1
#define PL_TACKLED 3
#define PL_GOALIE_CATCHING_BALL 4
#define PL_THROW_IN 5
#define PL_GOALIE_DIVING_HIGH 6
#define PL_GOALIE_DIVING_LOW 7
#define PL_STATIC_HEADING 8
#define PL_JUMP_HEADING 9
#define PL_DOWN 10
#define PL_GOALIE_CLAIMED 11
#define PL_BOOKED 12
#define PL_ROLLING_INJURED 13
#define PL_SAD 14
#define PL_HAPPY 15

// ---------------------------------------------------------------------------

// enum TacklingState, mappedto_71
#define TS_STARTED_TACKLING 0
#define TS_TACKLING_THE_BALL 1
#define TS_GOOD_TACKLE 2

// ---------------------------------------------------------------------------

// enum RefereeState, mappedto_22
#define REF_OFF_SCREEN 0
#define REF_INCOMING 1
#define REF_WAITING_PLAYER 2
#define REF_ABOUT_TO_GIVE_CARD 3
#define REF_BOOKING 4
#define REF_LEAVING 5

// ---------------------------------------------------------------------------

// enum Cards, mappedto_23
#define CARD_YELLOW 1
#define CARD_RED 2
#define CARD_SECOND_YELLOW 3

// ---------------------------------------------------------------------------

// enum DiyCompetitionTypes, mappedto_24
#define DIY_LEAGUE 0
#define DIY_CUP 1
#define DIY_TOURNAMENT 2

// ---------------------------------------------------------------------------

// enum AIL_preferences, mappedto_25
#define DIG_SERVICE_RATE 0
#define DIG_HARDWARE_SAMPLE_RATE 1
#define DIG_DMA_RESERVE 2
#define DIG_LATENCY 3
#define DIG_MIXER_CHANNELS 4
#define DIG_DEFAULT_VOLUME 5
#define DIG_RESAMPLING_TOLERANCE 6
#define DIG_USE_STEREO 7
#define DIG_USE_16_BITS 8
#define DIG_ALLOW_16_BIT_DMA 9
#define DIG_SS_LOCK 10
#define MDI_SERVICE_RATE 11
#define MDI_SEQUENCES 12
#define MDI_DEFAULT_VOLUME 13
#define MDI_QUANT_ADVANCE 14
#define MDI_ALLOW_LOOP_BRANCHING 15
#define MDI_DEFAULT_BEND_RANGE 16
#define AIL_SCAN_FOR_HARDWARE 17
#define AIL_ALLOW_VDM_EXECUTION 18

// ---------------------------------------------------------------------------

// enum GoalTypes, mappedto_57
#define GT_REGULAR 0
#define GT_PENALTY 1
#define GT_OWN_GOAL 2

// ---------------------------------------------------------------------------

// enum AIL_SampleStatusFlags, mappedto_58
#define SMP_FREE 1
#define SMP_DONE 2
#define SMP_PLAYING 4
#define SMP_STOPPED 8

// ---------------------------------------------------------------------------

// enum AIL_DigitalFormat, mappedto_60
#define DIG_F_MONO_8 0
#define DIG_F_MONO_16 1
#define DIG_F_STEREO_8 2
#define DIG_F_STEREO_16 3

// ---------------------------------------------------------------------------

// enum GameControls, mappedto_66
#define NO_CONTROLS_SELECTED 0
#define KEYBOARD_ONLY 1
#define JOYPAD_ONLY 2
#define JOYPAD_AND_KEYBOARD 3
#define KEYBOARD_AND_JOYPAD 4
#define TWO_JOYPADS 5
#define MOUSE 6

// ---------------------------------------------------------------------------

// enum StringFlags, mappedto_67
#define STR_COLOR_MASK 0x0F
#define STR_FLAGS_MASK 0x0F0
#define STR_ALIGN_RIGHT 0x4000
#define STR_ALIGN_LEFT 0x8000

// ---------------------------------------------------------------------------

// enum MenuBackgroundColors, mappedto_68
#define COLOR_ORANGE 6
#define COLOR_DARK_BLUE 8
#define COLOR_PINK_GRAYISH 9
#define COLOR_RED 10
#define COLOR_PURPLISH 11
#define COLOR_LIGHT_BLUE 13
#define COLOR_GREEN 14
#define COLOR_YELLOW 15
