// automatically generated by ida2asm, do not edit!

#pragma once

#include "swos.h"

namespace SwosVM {

constexpr int kNum68kRegisters = 15;
constexpr int k68kRegisterTotalSize = kNum68kRegisters * 4;using RegisterSet68k = std::array<Register, kNum68kRegisters>;

inline void store68kRegistersTo(RegisterSet68k& regs)
{
    regs[0] = A0; regs[1] = A1; regs[2] = A2; regs[3] = A3;
    regs[4] = A4; regs[5] = A5; regs[6] = A6; regs[7] = D0;
    regs[8] = D1; regs[9] = D2; regs[10] = D3; regs[11] = D4;
    regs[12] = D5; regs[13] = D6; regs[14] = D7;
}

inline void load68kRegistersFrom(const RegisterSet68k& regs)
{
    A0 = regs[0]; A1 = regs[1]; A2 = regs[2]; A3 = regs[3];
    A4 = regs[4]; A5 = regs[5]; A6 = regs[6]; D0 = regs[7];
    D1 = regs[8]; D2 = regs[9]; D3 = regs[10]; D4 = regs[11];
    D5 = regs[12]; D6 = regs[13]; D7 = regs[14];
}

struct Flags
{
    bool carry;
    bool zero;
    bool sign;
    bool overflow;
};

//    SWOS VM memory layout:
//    +---------------+
//    |   safe area   |
//    +---------------+
//    |   basic mem   |    (all the variables)
//    +---------------+
//    |   safe area   |
//    +---------------+
//    |  extended mem |    (memory the game allocates from the OS)
//    +---------------+
//    |   safe area   |
//    +---------------+
//    | pointer pool  |    (native pointers, pointing outside the SWOS VM)
//    |     area      |
//    +---------------+
//    |   safe area   |
//    +---------------+
//    |  dynamic mem  |    (memory allocated by the code outside the SWOS VM)
//    |  (allocated)  |
//    +---------------+
//    |   safe area   |
//    +---------------+

constexpr size_t kSafeMemAreaSize = 256;
constexpr size_t kMemStartOfs = kSafeMemAreaSize;
constexpr size_t kBasicMemSize = 540888;
constexpr size_t kPointerPoolSize = 256;
constexpr size_t kExtendedMemSize = 60000;
constexpr size_t kDynamicMemSize = 1024;
constexpr size_t kMemSize = kBasicMemSize + kPointerPoolSize + kExtendedMemSize + kDynamicMemSize + 5 * kSafeMemAreaSize;

static_assert(256 % sizeof(void *) == 0, "Run to the Hills");
static_assert(540888 % sizeof(void *) == 0, "Run to the Hills");
static_assert(256 % sizeof(void *) == 0, "Run to the Hills");
static_assert(60000 % sizeof(void *) == 0, "Run to the Hills");
static_assert(1024 % sizeof(void *) == 0, "Run to the Hills");

extern uint8_t g_memByte[kMemSize];

static uint8_t * const kMemStart = g_memByte + kSafeMemAreaSize;
static uint8_t * const kExtendedMemStart = kMemStart + kBasicMemSize + kSafeMemAreaSize;
static uint8_t * const kPointerPoolStart = kExtendedMemStart + kExtendedMemSize + kSafeMemAreaSize;
static uint8_t * const kDynamicMemStart = kPointerPoolStart + kPointerPoolSize + kSafeMemAreaSize;

#pragma pack(push, 1)
struct SwosVariables
{
    byte filler__0000[4201];
    const char aChairmanScenes[16];
    byte filler__0001[31];
    const char aReturnToGame[15];
    byte filler__0002[3902];
    const char aFriendlyDiyGam[25];
    byte filler__0003[409];
    const char aLoadHighlights[25];
    const char aSaveHighlights[25];
    const char aViewHighlights[25];
    const char aNotAHighlights[36];
    const char aHigh[7];
    byte filler__0004[6360];
    const char aDiy[7];
    const char aPreset[7];
    byte filler__0005[14];
    const char aTact[7];
    byte filler__0006[1127];
    const char aReplay[12];
    byte filler__0007[524];
    const char aFriendly[20];
    byte filler__0008[139];
    const char aOk[6];
    byte filler__0009[16];
    const char aExit[6];
    const char aCancel[9];
    byte filler__0010[29];
    const char aDiyCompetition[22];
    byte filler__0011[174];
    const char aAbort[10];
    byte filler__0012[21];
    const char aPlus[2];
    const char aMinus[2];
    byte filler__0013[198];
    const char aEditTactics[17];
    byte filler__0014[1104];
    const char aCareer[19];
    byte filler__0015[276];
    const char aSeason[13];
    byte filler__0016[13];
    const char aEditCustomTeam[18];
    const char aPresetCompetit[21];
    const char aOptions[17];
    const char aHighlights[17];
    byte filler__0017[685];
    const char aLoadOldCompeti[24];
    byte filler__0018[8];
    const char aSave[8];
    byte filler__0019[4919];
    const char aCustom[7];
    byte filler__0020[12011];
    word careerFileBuffer;
    byte filler__0021[55114];
    word coachOrPlayer;
    byte filler__0022[39];
    byte plNationality;
    byte filler__0023[1034];
    char careerTeam[1292];
    byte filler__0024[4128];
    TeamFile currentTeam;
    byte filler__0025[642];
    word currentTeamNumber;
    byte filler__0026[27022];
    word competitionFileBuffer;
    word competitionOver;
    byte filler__0027[2896];
    word inFriendlyMenu;
    word isNationalTeam;
    word g_gameType;
    byte filler__0028[4];
    TeamTactics USER_A;
    byte filler__0029[1850];
    int16_t g_gameLength;
    int16_t g_autoReplays;
    byte filler__0030[2];
    int16_t g_autoSaveHighlights;
    int16_t g_allPlayerTeamsEqual;
    int16_t g_pitchType;
    byte filler__0031[4];
    byte seed2;
    byte randXorIndex2;
    byte randXorKey2;
    byte filler__0032[1];
    word randomSeed;
    byte filler__0033[18];
    dword selTeamsPtr;
    byte filler__0034[13];
    word trainingGameCopy;
    word g_numSelectedTeams;
    char g_selectedTeams[68400];
    byte filler__0035[1];
    SwosDataPointer<char> dosMemOfs60c00h;
    byte filler__0036[52212];
    word playGame;
    int16_t fireCounter;
    int16_t menuControlsDirection2;
    int16_t menuControlsDirection;
    word fire;
    word shortFire;
    word longFireTime;
    word longFireFlag;
    byte up;
    byte down;
    byte left;
    byte right;
    byte filler__0037[2];
    word fireResetFlag;
    word controlMask;
    byte filler__0038[64104];
    word twoPlayers;
    byte filler__0039[394];
    char importTacticsFilename[256];
    byte filler__0040[14];
    word dseg_10E846;
    word dseg_10E848;
    byte filler__0041[410];
    word g_exitMenu;
    byte filler__0042[6306];
    word teamsLoaded;
    word poolplyrLoaded;
    word frameCount;
    word lastFrameTicks;
    word lastGameTick;
    word currentGameTick;
    word currentTick;
    byte filler__0043[8];
    SwosDataPointer<SwosDataPointer<SpriteGraphics>> g_spriteGraphicsPtr;
    byte pl1Fire;
    byte pl2Fire;
    byte filler__0044[96];
    word leaveFireFlag;
    word skipFireEveryOtherFrame;
    word pl1SkipFireCounter;
    word pl2SkipFireCounter;
    byte filler__0045[46];
    FixedPoint kGoalkeeperDiveDeltas[8];
    byte filler__0046[1456];
    word kKeeperSaveDistance;
    byte filler__0047[66];
    word kBallGroundConstant;
    word kBallAirConstant;
    byte filler__0048[8];
    word ballSpeedBounceFactor;
    word ballBounceFactor;
    word pitchBallSpeedFactor;
    byte filler__0049[2];
    dword kGravityConstant;
    byte filler__0050[316];
    Sprite playerMarkSprite;
    byte filler__0051[2];
    Sprite currentPlayerNameSprite;
    byte filler__0052[2];
    Sprite team1CurPlayerNumSprite;
    byte filler__0053[2];
    Sprite team2CurPlayerNumSprite;
    byte filler__0054[110];
    Sprite goalie1Sprite;
    byte filler__0055[2];
    Sprite team1Player2Sprite;
    byte filler__0056[2];
    Sprite team1Player3Sprite;
    byte filler__0057[2];
    Sprite team1Player4Sprite;
    byte filler__0058[2];
    Sprite team1Player5Sprite;
    byte filler__0059[2];
    Sprite team1Player6Sprite;
    byte filler__0060[2];
    Sprite team1Player7Sprite;
    byte filler__0061[2];
    Sprite team1Player8Sprite;
    byte filler__0062[2];
    Sprite team1Player9Sprite;
    byte filler__0063[2];
    Sprite team1Player10Sprite;
    byte filler__0064[2];
    Sprite team1Player11Sprite;
    byte filler__0065[2];
    Sprite goalie2Sprite;
    byte filler__0066[2];
    Sprite team2Player2Sprite;
    byte filler__0067[2];
    Sprite team2Player3Sprite;
    byte filler__0068[2];
    Sprite team2Player4Sprite;
    byte filler__0069[2];
    Sprite team2Player5Sprite;
    byte filler__0070[2];
    Sprite team2Player6Sprite;
    byte filler__0071[2];
    Sprite team2Player7Sprite;
    byte filler__0072[2];
    Sprite team2Player8Sprite;
    byte filler__0073[2];
    Sprite team2Player9Sprite;
    byte filler__0074[2];
    Sprite team2Player10Sprite;
    byte filler__0075[2];
    Sprite team2Player11Sprite;
    byte filler__0076[2];
    Sprite ballSprite;
    byte filler__0077[2];
    Sprite ballShadowSprite;
    byte filler__0078[662];
    Sprite goal1TopSprite;
    byte filler__0079[2];
    Sprite goal2BottomSprite;
    byte filler__0080[2];
    SwosDataPointer<Sprite> team1SpritesTable[11];
    SwosDataPointer<Sprite> team2SpritesTable[11];
    byte filler__0081[454];
    word teamsType;
    byte filler__0082[60];
    word abortSelectTeams;
    byte filler__0083[926];
    PositionsTable positionsTable;
    byte filler__0084[380];
    SwosDataPointer<const char> playerPositionsStringTable[1];
    byte filler__0085[792];
    TeamGame topTeamInGame;
    TeamGame bottomTeamInGame;
    char gameName[40];
    char gameRound[40];
    word gameMinSubstitutes;
    word gameMaxSubstitutes;
    word squadChangesAllowed;
    byte filler__0086[2];
    SwosDataPointer<TeamFile> playMatchTeam1Ptr;
    SwosDataPointer<TeamFile> playMatchTeam2Ptr;
    byte filler__0087[18];
    word playerNumThatStarted;
    byte filler__0088[6];
    word diySelected;
    byte filler__0089[212];
    SwosDataPointer<TeamGame> winningTeamPtr;
    byte filler__0090[8];
    word statsTeam1GoalsCopy;
    word statsTeam2GoalsCopy;
    word statsTeam1Goals;
    word statsTeam2Goals;
    word team1TotalGoals;
    word team2TotalGoals;
    word team1GoalsDigit2;
    word team2GoalsDigit2;
    word team1GoalsDigit1;
    word team2GoalsDigit1;
    byte filler__0091[616];
    char g_pitchDatBuffer[10032];
    char g_currentMenu[6500];
    byte filler__0092[12944];
    char skillsPerQuadrant[245];
    byte filler__0093[5779];
    SwosDataPointer<TeamTactics> g_tacticsTable[18];
    byte filler__0094[5580];
    word dseg_11F41C;
    byte filler__0095[294];
    const char saveFileTitle[70];
    byte filler__0096[78];
    SwosDataPointer<void> chooseTacticsTeamPtr;
    byte filler__0097[1054];
    byte kRandomTable[256];
    byte filler__0098[69096];
    word topTeamCoachNo;
    word bottomTeamCoachNo;
    word topTeamPlayerNo;
    word bottomTeamPlayerNo;
    word plg_D0_param;
    word isGameFriendly;
    word playing2ndGame;
    word secondLeg;
    word gamePitchTypeOrSeason;
    int16_t gamePitchType;
    word gameSeason;
    word gameCanceled;
    word pl1Tactics;
    word pl2Tactics;
    word team1Computer;
    word team2Computer;
    word gameLengthInGame;
    word extraTimeState;
    int16_t penaltiesState;
    word team1GoalsFirstLeg;
    word team2GoalsFirstLeg;
    word team1PenaltyGoals;
    word team2PenaltyGoals;
    word plg_D3_param;
    word team1NumAllowedInjuries;
    word team2NumAllowedInjuries;
    byte filler__0099[398];
    SwosDataPointer<TeamGame> topTeamPtr;
    SwosDataPointer<TeamGame> bottomTeamPtr;
    word team1NumSubs;
    word team2NumSubs;
    byte filler__0100[4];
    int16_t statsTimer;
    int16_t resultTimer;
    int16_t timeVar;
    byte filler__0101[50];
    int16_t cameraXVelocity;
    int16_t cameraYVelocity;
    word hideBall;
    word dseg_130FF9;
    word lastPlayerTurnFlags;
    byte filler__0102[2];
    union {
        char frameIndicesTablesStart[1];
        byte filler__0103[2];
    };
    byte filler__0104[2326];
    int16_t refSecondYellowFrames[1];
    byte filler__0105[56];
    union {
        char animTablesStart[1];
        byte filler__0106[2];
    };
    byte filler__0107[1038];
    PlayerAnimationTable playerNormalStandingAnimTable;
    byte filler__0108[2374];
    word refComingAnimTable;
    byte filler__0109[32];
    word refWaitingAnimTable;
    byte filler__0110[48];
    word refYellowCardAnimTable;
    byte filler__0111[32];
    word refRedCardAnimTable;
    byte filler__0112[32];
    word refSecondYellowAnimTable;
    byte filler__0113[32];
    union {
        char animTablesEnd[1];
        word userRequestedReplay;
    };
    word cameraCoordinatesValid;
    byte filler__0114[44];
    int16_t ballMovingFrameIndices[1];
    byte filler__0115[8];
    int16_t ballStaticFrameIndices[1];
    byte filler__0116[4];
    int16_t goalCounter;
    byte filler__0117[2];
    word goalCameraMode;
    word averagePlayerPrice;
    SwosDataPointer<TeamFile> gameTeam1;
    SwosDataPointer<TeamFile> gameTeam2;
    word gameRandValue;
    word team1AppPercent;
    word team2AppPercent;
    byte filler__0118[238];
    SwosDataPointer<MenuEntry> previousMenuItem;
    byte filler__0119[4];
    word goalTypeScored;
    byte filler__0120[6];
    word loadCrowdChantSampleFlag;
    byte filler__0121[4];
    word stateGoal;
    byte filler__0122[74];
    word g_skipNonCompetitionFiles;
    byte filler__0123[2];
    word careerTeamCoachOnly;
    byte filler__0124[296];
    word g_exitGameFlag;
    byte filler__0125[6];
    SwosDataPointer<TeamGeneralInfo> teamScoredDataPtr;
    byte filler__0126[872];
    word goalScored;
    word runSlower;
    SwosDataPointer<Sprite> lastPlayerScored;
    word lastTeamScoredNumber;
    word nobodysBallTimer;
    byte filler__0127[4];
    SwosDataPointer<SpriteGraphics> spritesIndex[1];
    byte filler__0128[8408];
    word g_trainingGame;
    word g_allowShorterMenuItemsWithFrames;
    byte filler__0129[13];
    char jumpHeaderTeam1UpFrames[1];
    byte filler__0130[1218];
    word choosingPreset;
    byte filler__0131[18184];
    word menuCursorFrame;
    byte filler__0132[4];
    word goodPassTimer;
    int16_t playingCornerSample;
    int16_t playingThrowInSample;
    int16_t playingGoodPassTimer;
    SwosDataPointer<const char> soundEffectsTable[1];
    byte filler__0133[44];
    SwosDataPointer<const char> introTeamChantsTable[1];
    byte filler__0134[20];
    SwosDataPointer<const char> resultChantFilenames[1];
    byte filler__0135[28];
    SwosDataPointer<const char> endGameCrowdSamples[1];
    byte filler__0136[606];
    const char aSensibleWorldOfSoccerV2_0[30];
    byte filler__0137[4];
    word instantReplayFlag;
    word saveHighlightScene;
    word fadeAndSaveHighlightScene;
    word spaceReplayTimer;
    word playHighlightFlag;
    word g_inSubstitutesMenu;
    word g_cameraLeavingSubsTimer;
    word g_waitForPlayerToGoInTimer;
    word plComingX;
    word plComingY;
    word plSubstitutedX;
    word plSubstitutedY;
    int16_t g_substituteInProgress;
    byte filler__0138[2];
    SwosDataPointer<Sprite> substitutedPlSprite;
    SwosDataPointer<TeamGeneralInfo> teamThatSubstitutes;
    byte seed;
    byte filler__0139[543];
    word pitchTypeOrSeason;
    byte filler__0140[2];
    word friendlySeason;
    word minSubstitutes;
    word maxSubstitutes;
    byte filler__0141[7362];
    word isFirstPlayerChoosingTeam;
    byte filler__0142[10];
    char playMatchMenu[1];
    byte filler__0143[13927];
    PackedMenu diyCompetitionMenu;
    byte filler__0144[488];
    word chosenTactics;
    byte filler__0145[12];
    word flipOnOff;
    byte filler__0146[12474];
    word showFansCounter;
    word animPatternsState;
    byte filler__0147[1726];
    SwosDataPointer<Sprite> currentScorer;
    SwosDataPointer<TeamGeneralInfo> lastTeamScored;
    SwosDataPointer<Sprite> lastPlayerBeforeGoalkeeper;
    TeamStatsData team1StatsData;
    byte filler__0148[2];
    TeamStatsData team2StatsData;
    byte filler__0149[2];
    TeamGeneralInfo topTeamData;
    byte filler__0150[3];
    TeamGeneralInfo bottomTeamData;
    byte filler__0151[7];
    SwosDataPointer<TeamGeneralInfo> lastTeamPlayed;
    SwosDataPointer<Sprite> lastPlayerPlayed;
    word penalty;
    byte filler__0152[2];
    word gameNotInProgressCounterWriteOnly;
    word fireBlocked;
    SwosDataPointer<TeamGeneralInfo> lastTeamPlayedBeforeBreak;
    word stoppageTimerTotal;
    word stoppageTimerActive;
    GameState gameStatePl;
    GameState gameState;
    word breakCameraMode;
    word stoppageEventTimer;
    word foulXCoordinate;
    word foulYCoordinate;
    int16_t cameraDirection;
    word playerTurnFlags;
    byte filler__0153[4];
    word substitutedPlDestX;
    word substitutedPlDestY;
    byte filler__0154[4];
    word teamStarting;
    word teamPlayingUp;
    word playingPenalties;
    word dontShowScorers;
    byte filler__0155[468];
    word refState;
    byte filler__0156[16];
    word whichCard;
    SwosDataPointer<Sprite> bookedPlayer;
    SwosDataPointer<TeamGeneralInfo> lastTeamBooked;
    word refTimer;
    word playerCardChance;
    byte filler__0157[42];
    int16_t playerXQuadrantsCoordinates[15];
    int16_t playerYQuadrantCoordinates[16];
    int16_t ballQuadrantIndex;
    byte filler__0158[4];
    int16_t playerXQuadrantOffset;
    int16_t playerYQuadrantOffset;
    byte filler__0159[298];
    int16_t kTeamsStartingCoordinates[44];
    SwosDataPointer<int16_t> kGoalieSkillTables[8];
    byte filler__0160[562];
    word strikeDestX;
    byte filler__0161[14];
    word ballInGoalkeeperArea;
    byte filler__0162[1860];
    word playersLeavingPitchBottom[22];
    word playersLeavingPitchTop[22];
    byte filler__0163[252];
    int16_t kPlayerShotChanceTable[30];
    word AI_turnDirection;
    byte filler__0164[13814];
    int32_t penaltiesInterval;
    int32_t initalKickInterval;
    int32_t goalCameraInterval;
    int32_t letPlayerControlCameraInterval;
    int32_t playerDownTacklingInterval;
    int32_t playerDownHeadingInterval;
    int32_t clearResultInterval;
    int32_t clearResultHalftimeInterval;
};
#pragma pack(pop)

enum Offsets : uint32_t
{
    aChairmanScenes = 4201,
    aReturnToGame = 4248,
    aFriendlyDiyGam = 8165,
    aLoadHighlights = 8599,
    aSaveHighlights = 8624,
    aViewHighlights = 8649,
    aNotAHighlights = 8674,
    aHigh = 8710,
    aDiy = 15077,
    aPreset = 15084,
    aTact = 15105,
    aReplay = 16239,
    aFriendly = 16775,
    aOk = 16934,
    aExit = 16956,
    aCancel = 16962,
    aDiyCompetition = 17000,
    aAbort = 17196,
    aPlus = 17227,
    aMinus = 17229,
    aEditTactics = 17429,
    aCareer = 18550,
    aSeason = 18845,
    aEditCustomTeam = 18871,
    aPresetCompetit = 18889,
    aOptions = 18910,
    aHighlights = 18927,
    aLoadOldCompeti = 19629,
    aSave = 19661,
    aCustom = 24588,
    careerFileBuffer = 36606,
    coachOrPlayer = 91722,
    plNationality = 91763,
    careerTeam = 92798,
    currentTeam = 98218,
    currentTeamNumber = 99544,
    competitionFileBuffer = 126568,
    competitionOver = 126570,
    inFriendlyMenu = 129468,
    isNationalTeam = 129470,
    g_gameType = 129472,
    USER_A = 129478,
    g_gameLength = 131698,
    g_autoReplays = 131700,
    g_autoSaveHighlights = 131704,
    g_allPlayerTeamsEqual = 131706,
    g_pitchType = 131708,
    seed2 = 131714,
    randXorIndex2 = 131715,
    randXorKey2 = 131716,
    randomSeed = 131718,
    selTeamsPtr = 131738,
    trainingGameCopy = 131755,
    g_numSelectedTeams = 131757,
    g_selectedTeams = 131759,
    dosMemOfs60c00h = 200160,
    playGame = 252376,
    fireCounter = 252378,
    menuControlsDirection2 = 252380,
    menuControlsDirection = 252382,
    fire = 252384,
    shortFire = 252386,
    longFireTime = 252388,
    longFireFlag = 252390,
    up = 252392,
    down = 252393,
    left = 252394,
    right = 252395,
    fireResetFlag = 252398,
    controlMask = 252400,
    twoPlayers = 316506,
    importTacticsFilename = 316902,
    dseg_10E846 = 317172,
    dseg_10E848 = 317174,
    g_exitMenu = 317586,
    teamsLoaded = 323894,
    poolplyrLoaded = 323896,
    frameCount = 323898,
    lastFrameTicks = 323900,
    lastGameTick = 323902,
    currentGameTick = 323904,
    currentTick = 323906,
    g_spriteGraphicsPtr = 323916,
    pl1Fire = 323920,
    pl2Fire = 323921,
    leaveFireFlag = 324018,
    skipFireEveryOtherFrame = 324020,
    pl1SkipFireCounter = 324022,
    pl2SkipFireCounter = 324024,
    kGoalkeeperDiveDeltas = 324072,
    kKeeperSaveDistance = 325560,
    kBallGroundConstant = 325628,
    kBallAirConstant = 325630,
    ballSpeedBounceFactor = 325640,
    ballBounceFactor = 325642,
    pitchBallSpeedFactor = 325644,
    kGravityConstant = 325648,
    playerMarkSprite = 325968,
    currentPlayerNameSprite = 326080,
    team1CurPlayerNumSprite = 326192,
    team2CurPlayerNumSprite = 326304,
    goalie1Sprite = 326524,
    team1Player2Sprite = 326636,
    team1Player3Sprite = 326748,
    team1Player4Sprite = 326860,
    team1Player5Sprite = 326972,
    team1Player6Sprite = 327084,
    team1Player7Sprite = 327196,
    team1Player8Sprite = 327308,
    team1Player9Sprite = 327420,
    team1Player10Sprite = 327532,
    team1Player11Sprite = 327644,
    goalie2Sprite = 327756,
    team2Player2Sprite = 327868,
    team2Player3Sprite = 327980,
    team2Player4Sprite = 328092,
    team2Player5Sprite = 328204,
    team2Player6Sprite = 328316,
    team2Player7Sprite = 328428,
    team2Player8Sprite = 328540,
    team2Player9Sprite = 328652,
    team2Player10Sprite = 328764,
    team2Player11Sprite = 328876,
    ballSprite = 328988,
    ballShadowSprite = 329100,
    goal1TopSprite = 329872,
    goal2BottomSprite = 329984,
    team1SpritesTable = 330096,
    team2SpritesTable = 330140,
    teamsType = 330638,
    abortSelectTeams = 330700,
    positionsTable = 331628,
    playerPositionsStringTable = 332080,
    topTeamInGame = 332876,
    bottomTeamInGame = 334580,
    gameName = 336284,
    gameRound = 336324,
    gameMinSubstitutes = 336364,
    gameMaxSubstitutes = 336366,
    squadChangesAllowed = 336368,
    playMatchTeam1Ptr = 336372,
    playMatchTeam2Ptr = 336376,
    playerNumThatStarted = 336398,
    diySelected = 336406,
    winningTeamPtr = 336620,
    statsTeam1GoalsCopy = 336632,
    statsTeam2GoalsCopy = 336634,
    statsTeam1Goals = 336636,
    statsTeam2Goals = 336638,
    team1TotalGoals = 336640,
    team2TotalGoals = 336642,
    team1GoalsDigit2 = 336644,
    team2GoalsDigit2 = 336646,
    team1GoalsDigit1 = 336648,
    team2GoalsDigit1 = 336650,
    g_pitchDatBuffer = 337268,
    g_currentMenu = 347300,
    skillsPerQuadrant = 366744,
    g_tacticsTable = 372768,
    dseg_11F41C = 378420,
    saveFileTitle = 378716,
    chooseTacticsTeamPtr = 378864,
    kRandomTable = 379922,
    topTeamCoachNo = 449274,
    bottomTeamCoachNo = 449276,
    topTeamPlayerNo = 449278,
    bottomTeamPlayerNo = 449280,
    plg_D0_param = 449282,
    isGameFriendly = 449284,
    playing2ndGame = 449286,
    secondLeg = 449288,
    gamePitchTypeOrSeason = 449290,
    gamePitchType = 449292,
    gameSeason = 449294,
    gameCanceled = 449296,
    pl1Tactics = 449298,
    pl2Tactics = 449300,
    team1Computer = 449302,
    team2Computer = 449304,
    gameLengthInGame = 449306,
    extraTimeState = 449308,
    penaltiesState = 449310,
    team1GoalsFirstLeg = 449312,
    team2GoalsFirstLeg = 449314,
    team1PenaltyGoals = 449316,
    team2PenaltyGoals = 449318,
    plg_D3_param = 449320,
    team1NumAllowedInjuries = 449322,
    team2NumAllowedInjuries = 449324,
    topTeamPtr = 449724,
    bottomTeamPtr = 449728,
    team1NumSubs = 449732,
    team2NumSubs = 449734,
    statsTimer = 449740,
    resultTimer = 449742,
    timeVar = 449744,
    cameraXVelocity = 449796,
    cameraYVelocity = 449798,
    hideBall = 449800,
    dseg_130FF9 = 449802,
    lastPlayerTurnFlags = 449804,
    frameIndicesTablesStart = 449808,
    refSecondYellowFrames = 452136,
    animTablesStart = 452194,
    playerNormalStandingAnimTable = 453234,
    refComingAnimTable = 455738,
    refWaitingAnimTable = 455772,
    refYellowCardAnimTable = 455822,
    refRedCardAnimTable = 455856,
    refSecondYellowAnimTable = 455890,
    animTablesEnd = 455924,
    userRequestedReplay = 455924,
    cameraCoordinatesValid = 455926,
    ballMovingFrameIndices = 455972,
    ballStaticFrameIndices = 455982,
    goalCounter = 455988,
    goalCameraMode = 455992,
    averagePlayerPrice = 455994,
    gameTeam1 = 455996,
    gameTeam2 = 456000,
    gameRandValue = 456004,
    team1AppPercent = 456006,
    team2AppPercent = 456008,
    previousMenuItem = 456248,
    goalTypeScored = 456256,
    loadCrowdChantSampleFlag = 456264,
    stateGoal = 456270,
    g_skipNonCompetitionFiles = 456346,
    careerTeamCoachOnly = 456350,
    g_exitGameFlag = 456648,
    teamScoredDataPtr = 456656,
    goalScored = 457532,
    runSlower = 457534,
    lastPlayerScored = 457536,
    lastTeamScoredNumber = 457540,
    nobodysBallTimer = 457542,
    spritesIndex = 457548,
    g_trainingGame = 465960,
    g_allowShorterMenuItemsWithFrames = 465962,
    jumpHeaderTeam1UpFrames = 465977,
    choosingPreset = 467196,
    menuCursorFrame = 485382,
    goodPassTimer = 485388,
    playingCornerSample = 485390,
    playingThrowInSample = 485392,
    playingGoodPassTimer = 485394,
    soundEffectsTable = 485396,
    introTeamChantsTable = 485444,
    resultChantFilenames = 485468,
    endGameCrowdSamples = 485500,
    aSensibleWorldOfSoccerV2_0 = 486110,
    instantReplayFlag = 486144,
    saveHighlightScene = 486146,
    fadeAndSaveHighlightScene = 486148,
    spaceReplayTimer = 486150,
    playHighlightFlag = 486152,
    g_inSubstitutesMenu = 486154,
    g_cameraLeavingSubsTimer = 486156,
    g_waitForPlayerToGoInTimer = 486158,
    plComingX = 486160,
    plComingY = 486162,
    plSubstitutedX = 486164,
    plSubstitutedY = 486166,
    g_substituteInProgress = 486168,
    substitutedPlSprite = 486172,
    teamThatSubstitutes = 486176,
    seed = 486180,
    pitchTypeOrSeason = 486724,
    friendlySeason = 486728,
    minSubstitutes = 486730,
    maxSubstitutes = 486732,
    isFirstPlayerChoosingTeam = 494096,
    playMatchMenu = 494108,
    diyCompetitionMenu = 508036,
    chosenTactics = 508540,
    flipOnOff = 508554,
    showFansCounter = 521030,
    animPatternsState = 521032,
    currentScorer = 522760,
    lastTeamScored = 522764,
    lastPlayerBeforeGoalkeeper = 522768,
    team1StatsData = 522772,
    team2StatsData = 522788,
    topTeamData = 522804,
    bottomTeamData = 522952,
    lastTeamPlayed = 523104,
    lastPlayerPlayed = 523108,
    penalty = 523112,
    gameNotInProgressCounterWriteOnly = 523116,
    fireBlocked = 523118,
    lastTeamPlayedBeforeBreak = 523120,
    stoppageTimerTotal = 523124,
    stoppageTimerActive = 523126,
    gameStatePl = 523128,
    gameState = 523130,
    breakCameraMode = 523132,
    stoppageEventTimer = 523134,
    foulXCoordinate = 523136,
    foulYCoordinate = 523138,
    cameraDirection = 523140,
    playerTurnFlags = 523142,
    substitutedPlDestX = 523148,
    substitutedPlDestY = 523150,
    teamStarting = 523156,
    teamPlayingUp = 523158,
    playingPenalties = 523160,
    dontShowScorers = 523162,
    refState = 523632,
    whichCard = 523650,
    bookedPlayer = 523652,
    lastTeamBooked = 523656,
    refTimer = 523660,
    playerCardChance = 523662,
    playerXQuadrantsCoordinates = 523706,
    playerYQuadrantCoordinates = 523736,
    ballQuadrantIndex = 523768,
    playerXQuadrantOffset = 523774,
    playerYQuadrantOffset = 523776,
    kTeamsStartingCoordinates = 524076,
    kGoalieSkillTables = 524164,
    strikeDestX = 524758,
    ballInGoalkeeperArea = 524774,
    playersLeavingPitchBottom = 526636,
    playersLeavingPitchTop = 526680,
    kPlayerShotChanceTable = 526976,
    AI_turnDirection = 527036,
    penaltiesInterval = 540852,
    initalKickInterval = 540856,
    goalCameraInterval = 540860,
    letPlayerControlCameraInterval = 540864,
    playerDownTacklingInterval = 540868,
    playerDownHeadingInterval = 540872,
    clearResultInterval = 540876,
    clearResultHalftimeInterval = 540880,
};

static_assert(offsetof(SwosVariables, aChairmanScenes) == 4201, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, aDiyCompetition) == 17000, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, plNationality) == 91763, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, randXorIndex2) == 131715, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, up) == 252392, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, currentGameTick) == 323904, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, kGravityConstant) == 325648, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, goalie2Sprite) == 327756, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, team2SpritesTable) == 330140, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, winningTeamPtr) == 336620, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, saveFileTitle) == 378716, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, pl2Tactics) == 449300, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, team2NumSubs) == 449734, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, refRedCardAnimTable) == 455856, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, goalTypeScored) == 456256, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, choosingPreset) == 467196, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, g_inSubstitutesMenu) == 486154, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, playMatchMenu) == 494108, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, gameNotInProgressCounterWriteOnly) == 523116, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, teamPlayingUp) == 523158, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, strikeDestX) == 524758, "Variable offsets are broken");
static_assert(offsetof(SwosVariables, clearResultHalftimeInterval) == 540880, "Variable offsets are broken");

enum class Procs : int
{
    AbortChooseTeamsFriendly = -2,
    AbortEditTactics = -3,
    AcceptJobOffer = -4,
    AcceptOffer = -5,
    AddInternationalPlayerAbroad = -6,
    AddInternationalPlayerHome = -7,
    ApplyTeamTactics = -8,
    AskForMore = -9,
    AssignFakeGoalsToScorers = -10,
    BuyOtherDomesticPlayer = -11,
    BuyOtherForeignPlayer = -12,
    BuyOtherPlayersAfterDrawCommon = -13,
    BuyOtherPlayersCommon = -14,
    BuyOtherPlayersFinish = -15,
    BuyOtherPlayersInit = -16,
    BuyPlayerExit = -17,
    BuyPlayerInit = -18,
    BuyPlayerMenu = -19,
    BuyPlayerViewSquad = -20,
    CalcMenuEntryAddress = -21,
    CareerGameListCommon = -22,
    CareerMenu = -23,
    CareerMenuFinish = -24,
    CareerMenuInit = -25,
    CareerOverFinish = -26,
    CareerOverInit = -27,
    ChairmanMemosContinue = -28,
    ChairmanMemosInit = -29,
    ChairmanMemosOnReturn = -30,
    ChangeAllPlTeamsEqual = -31,
    ChangeAutoReplays = -32,
    ChangeAutoSaveHighlights = -33,
    ChangeGameLength = -34,
    ChangeNationality = -35,
    ChangePitchType = -36,
    ChangeSex = -37,
    ChangeTeams = -38,
    ChooseTacticsInit = -39,
    ChooseTeamAndStartCareer = -40,
    ChooseTeamsFriendlyCommon = -41,
    ChooseTeamsFriendlyCommon2 = -42,
    ChooseTeamsFriendlyInit = -43,
    ChooseTeamsFriendlyInitFinish = -44,
    ChooseTeamsFriendlyOnSelect76 = -45,
    ChooseTeamsInit = -46,
    ChooseTeamsMenu = -47,
    ChooseTeamsPlayGame = -48,
    ChooseTeamsPlayMatchSelected = -49,
    ClubBusinessInit = -50,
    ClubBussinesMenu = -51,
    ClubTeams = -52,
    CoachOrPlayerCoach = -53,
    CommonMenuExit = -54,
    CompetitionInfo = -55,
    CompetitionTopGoalScorersExit = -56,
    CompetitionTopGoalScorersInit = -57,
    ConsiderJobOffer = -58,
    ConsiderOffer = -59,
    ContestMenuInit = -60,
    ContestMenuOnReturn = -61,
    ContestMenuScrollDown = -62,
    ContestMenuScrollUp = -63,
    ContinueCareer = -64,
    CopyTactics = -65,
    DIYCompetitionMenu = -66,
    DIYCupFinish = -67,
    DIYCupInit = -68,
    DIYCupOnSelect1 = -69,
    DIYCupOnSelect10 = -70,
    DIYCupOnSelect16 = -71,
    DIYCupOnSelect17 = -72,
    DIYCupOnSelect3 = -73,
    DIYCupOnSelect4 = -74,
    DIYCupOnSelect5 = -75,
    DIYCupOnSelect6 = -76,
    DIYCupOnSelect7 = -77,
    DIYCupOnSelect8 = -78,
    DIYCupOnSelect9 = -79,
    DIYLeagueChangePitchTypeOrSeason = -80,
    DIYLeagueTournament16BeforeDraw = -81,
    DIYLeagueTournamentExit = -82,
    DIYLeagueTournamentInit = -83,
    DIYLeagueTournamentMatch = -84,
    DIYLeagueTournamentNextMatch = -85,
    DIYLeagueTournamentOnRestore = -86,
    DIYLeagueTournamentOnSelect4 = -87,
    DIYLeagueTournamentResult = -88,
    DIYLeagueTournamentScrollDown = -89,
    DIYLeagueTournamentScrollUp = -90,
    DIYLeagueTournamentStats = -91,
    DIYLeagueTournamentViewHighlights = -92,
    DIYLeagueTournamentViewMatch = -93,
    DIYLeagueTournamentViewResult = -94,
    DesignDIYCupInit = -95,
    DesignDIYCupOK = -96,
    DesignDIYCupOnDraw = -97,
    DesignDIYCupOnSelect11 = -98,
    DesignDIYCupOnSelect13 = -99,
    DesignDIYCupOnSelect15 = -100,
    DesignDIYCupOnSelect2 = -101,
    DesignDIYCupOnSelect20 = -102,
    DesignDIYCupOnSelect21 = -103,
    DesignDIYCupOnSelect22 = -104,
    DesignDIYCupOnSelect3 = -105,
    DesignDIYCupOnSelect4 = -106,
    DesignDIYCupOnSelect48 = -107,
    DesignDIYCupOnSelect5 = -108,
    DesignDIYCupOnSelect7 = -109,
    DesignDIYCupOnSelect9 = -110,
    DesignDIYCupReinit = -111,
    DesignDIYLeagueChangeEndMonth = -112,
    DesignDIYLeagueChangeMaxSubstitutes = -113,
    DesignDIYLeagueChangeMinSubstitutes = -114,
    DesignDIYLeagueChangeNumPointsForWin = -115,
    DesignDIYLeagueChangeNumberOfTeams = -116,
    DesignDIYLeagueChangePitchType = -117,
    DesignDIYLeagueChangePlayEachTeam = -118,
    DesignDIYLeagueChangeStartMonth = -119,
    DesignDIYLeagueChooseTeams = -120,
    DesignDIYLeagueFinish = -121,
    DesignDIYLeagueInit = -122,
    DesignDIYLeagueOK = -123,
    DesignDIYLeagueSetName = -124,
    DesignDIYTournamentInit = -125,
    DesignDIYTournamentOK = -126,
    DesignDIYTournamentOnDraw = -127,
    DesignDIYTournamentOnSelect11 = -128,
    DesignDIYTournamentOnSelect13 = -129,
    DesignDIYTournamentOnSelect2 = -130,
    DesignDIYTournamentOnSelect20 = -131,
    DesignDIYTournamentOnSelect21 = -132,
    DesignDIYTournamentOnSelect23 = -133,
    DesignDIYTournamentOnSelect24 = -134,
    DesignDIYTournamentOnSelect25 = -135,
    DesignDIYTournamentOnSelect26 = -136,
    DesignDIYTournamentOnSelect28 = -137,
    DesignDIYTournamentOnSelect3 = -138,
    DesignDIYTournamentOnSelect4 = -139,
    DesignDIYTournamentOnSelect5 = -140,
    DesignDIYTournamentOnSelect7 = -141,
    DesignDIYTournamentOnSelect89 = -142,
    DesignDIYTournamentOnSelect9 = -143,
    DesignDIYTournamentOnSelect91 = -144,
    DesignDIYTournamentReinit = -145,
    DoGoalkeeperSprites = -146,
    DrawPlayerEntries = -147,
    EditCustomTeamMenu = -148,
    EditTacicsMovePlayersOrBall = -149,
    EditTactics28AfterDraw = -150,
    EditTactics2AfterDraw = -151,
    EditTacticsAfterDrawCommon = -152,
    EditTacticsAfterDrawPlayerNames = -153,
    EditTacticsCommon = -154,
    EditTacticsInPlayMatchMenu = -155,
    EditTacticsInit = -156,
    EditTacticsMenu = -157,
    EditTacticsOnRestore = -158,
    EditTacticsOnSelect28 = -159,
    EditTacticsPlayerNamesCommon = -160,
    EditTeamsCallback = -161,
    EditTeamsChangePlayerFace = -162,
    EditTeamsChangePlayerName = -163,
    EditTeamsChangeShirtsPrimary = -164,
    EditTeamsChangeShirtsSecondary = -165,
    EditTeamsChangeShortsPrimary = -166,
    EditTeamsChangeShortsSecondary = -167,
    EditTeamsChangeSocksPrimary = -168,
    EditTeamsChangeSocksSecondary = -169,
    EditTeamsFinish = -170,
    EditTeamsInit = -171,
    EditTeamsOK = -172,
    EditTeamsPlayersBeforeDraw = -173,
    EditTeamsSelectCoachName = -174,
    EditTeamsSelectPrimaryShirtType = -175,
    EditTeamsSelectSecondaryShirtType = -176,
    EditTeamsSelectTeamName = -177,
    EditTeamsUndo = -178,
    EditedCustomTeams = -179,
    EndFirstExtraTime = -180,
    EndFirstHalf = -181,
    EndOfGame = -182,
    ExitCareerMenu = -183,
    ExitChooseTacticsMenu = -184,
    ExitChooseTeams = -185,
    ExitChooseTeams2 = -186,
    ExitImportTactics = -187,
    ExitPlayMatch = -188,
    ExitSelectTeams = -189,
    ExtractSurname = -190,
    FillManagementRecordInfo = -191,
    FlipOnOff = -192,
    FriendlyMenu = -193,
    FriendlyMenuInit = -194,
    FriendlyMenuReinit = -195,
    FriendlyOK = -196,
    FriendlyPitchTypeProc = -197,
    GetAveragePlayerPriceInSelectedTeams = -198,
    GetNumberOfAvailablePlayers = -199,
    GiveFreeTransfer = -200,
    GoalkeeperClaimedTheBall = -201,
    GotJobOfferFinish = -202,
    GotJobOfferInit = -203,
    ImportTactics = -204,
    ImportTacticsSelectTactics = -205,
    ImportTeamsMenu = -206,
    InitAndPlayGame = -207,
    InitCareerVariables = -208,
    InitHighestScorersTable = -209,
    InitInGameTeamStructure = -210,
    InitUserTactics = -211,
    JobOffersAfterDrawCommon = -212,
    JobOffersCommon = -213,
    JobOffersExit = -214,
    JobOffersFinish = -215,
    JobOffersInit = -216,
    JobOffersMenu = -217,
    JobOffersMenuRetired = -218,
    LoadLiverpool = -219,
    LoadOldCompetitionMenu = -220,
    LoadTactics = -221,
    ManagementArrowDownSelect = -222,
    ManagementArrowUpSelect = -223,
    ManagementRecordInit = -224,
    ManagementRecordMenu = -225,
    MarkPlayer = -226,
    MaxSubstitutes = -227,
    MinSubstitutes = -228,
    NationalTeamAddPlayer = -229,
    NationalTeamAddPlayerAbroadOnSelect = -230,
    NationalTeamAddPlayerExit = -231,
    NationalTeamAddPlayerHomeOnSelect = -232,
    NationalTeamRemovePlayers = -233,
    NationalTeams = -234,
    NextMatch = -235,
    NullMenuInit = -236,
    OffersAfterDrawCommon = -237,
    OffersCommon = -238,
    OnSwapPlayer = -239,
    OriginalCustomTeams = -240,
    PitchTypeOrSeasonProc = -241,
    PlayMatch30AfterDraw = -242,
    PlayMatchChangeTactics = -243,
    PlayMatchMenu = -244,
    PlayMatchMenuInit = -245,
    PlayMatchMenuReinit = -246,
    PlayMatchOnSelect30 = -247,
    PlayMatchSelected = -248,
    PlayTrainingGame = -249,
    PlayerOffersAfterDrawCommon = -250,
    PlayerOffersInit = -251,
    PlayerOffersOnSelect10 = -252,
    PlayerOffersOnSelect11 = -253,
    PlayerOffersOnSelect12 = -254,
    PlayerOffersOnSelect13 = -255,
    PlayerOffersOnSelect8 = -256,
    PresetCompetitionMenu = -257,
    PutPlayerOnMarketMenu = -258,
    Randomize2 = -259,
    ReadTimerDelta = -260,
    RejectJobOffer = -261,
    RejectOffer = -262,
    ReturnFromViewOpponent = -263,
    SaveAndExitEditTactics = -264,
    SaveCareer = -265,
    SaveContest = -266,
    SeasonMenu = -267,
    SelTeamForTacticsCommon = -268,
    SelTeamForTacticsExit = -269,
    SelTeamForTacticsInit = -270,
    SelectCopyTactics = -271,
    SelectDiyCupMenu = -272,
    SelectDiyExitMenu = -273,
    SelectDiyLeagueMenu = -274,
    SelectDiyTournamentMenu = -275,
    SelectGoals = -276,
    SelectLeaguesCommon = -277,
    SelectNationalTeam25AfterDraw = -278,
    SelectNationalTeamAbort = -279,
    SelectNationalTeamAfterDrawCommon = -280,
    SelectNationalTeamCommon = -281,
    SelectNationalTeamExit = -282,
    SelectNationalTeamFinish = -283,
    SelectNationalTeamInit = -284,
    SelectNationalTeamOnSelect25 = -285,
    SelectTeamsCommon = -286,
    SelectTeamsInit = -287,
    SelectTeamsReinit = -288,
    SelectTraining = -289,
    SetDefaultNameAndSurname = -290,
    SetExitMenuFlag = -291,
    SetInGameTeamsPrimaryColors = -292,
    SetName = -293,
    SetNextPlayerFrame = -294,
    SetPlayerAnimationTable = -295,
    SetSurname = -296,
    SetTeamSecondaryColors = -297,
    ShowPlayerMarket = -298,
    Squad45AfterDraw = -299,
    SquadAfterDrawCommon = -300,
    SquadCommon = -301,
    SquadFinish = -302,
    SquadInit = -303,
    SquadMenu = -304,
    SquadOnSelect11 = -305,
    SquadOnSelect45 = -306,
    StartContest = -307,
    StartFirstExtraTime = -308,
    StartPenalties = -309,
    StartingMatch = -310,
    StatsExit = -311,
    StatsHighestScorerList = -312,
    StatsViewSquads = -313,
    TakeOffMarketMenu = -314,
    ThirdPartyOfferMenuAfterDrawCommon = -315,
    ThirdPartyOfferMenuExit = -316,
    ThirdPartyOfferMenuInit = -317,
    ThirdPartyOfferViewSquad = -318,
    TogglePlayerCoach = -319,
    TopGoalScorersBeforeDrawCommon = -320,
    TopGoalScorersExit = -321,
    TopGoalScorersInit = -322,
    TopGoalScorersMenu = -323,
    TransferMarketAfterDrawCommon = -324,
    TransferMarketCommon = -325,
    TransferMarketFinish = -326,
    TransferMarketInit = -327,
    TransferPlayerAfterDrawCommon = -328,
    TransferPlayerInit = -329,
    TransferPlayerOnSelect10 = -330,
    TransferPlayerOnSelect11 = -331,
    TransferPlayerOnSelect12 = -332,
    TransfersMenu = -333,
    UndoTactics = -334,
    UpdateBall = -335,
    UpdateCameraBreakMode = -336,
    UpdateControlledPlayer = -337,
    UpdateControlledPlayerNumbers = -338,
    UpdatePlayerBeingPassedTo = -339,
    UpdatePlayerInjuries = -340,
    UseMatchTeamSelect = -341,
    User_A_Tactics = -342,
    User_B_Tactics = -343,
    User_C_Tactics = -344,
    User_D_Tactics = -345,
    User_E_Tactics = -346,
    User_F_Tactics = -347,
    ViewCompetitionsMenu = -348,
    ViewCompetitionsMenuRetired = -349,
    ViewDomesticPlayerMarket = -350,
    ViewForeignPlayerMarket = -351,
    ViewFutureTeam = -352,
    ViewFutureTeamLeague = -353,
    ViewOffersMenu = -354,
    ViewOpponentsSelect = -355,
    ViewSelected = -356,
    ViewSelectedTeams = -357,
    ViewSquad21AfterDraw = -358,
    ViewSquadAfterDrawCommon = -359,
    ViewSquadCommon = -360,
    ViewSquadExitContinue = -361,
    ViewSquadInit = -362,
    ViewSquadOnSelect21 = -363,
    ViewWorldMenu = -364,
    ZeroOutStars = -365,
    cseg_2F0E2 = -366,
    cseg_2F194 = -367,
    cseg_2F3AB = -368,
    cseg_30BD1 = -369,
    cseg_375C2 = -370,
    cseg_3760C = -371,
    cseg_37B44 = -372,
    cseg_37B50 = -373,
    cseg_37B5C = -374,
    cseg_37B68 = -375,
    cseg_43F3E = -376,
    cseg_580EF = -377,
    cseg_59B41 = -378,
    cseg_59BFE = -379,
    cseg_59CA2 = -380,
    cseg_59CC7 = -381,
    cseg_59D8E = -382,
    cseg_59F61 = -383,
    cseg_5A017 = -384,
    cseg_605C0 = -385,
    cseg_6087D = -386,
    cseg_8F66C = -387,
    j_SetExitMenuFlag = -388,
    j_SetExitMenuFlag13 = -389,
    j_SetExitMenuFlag2 = -390,
    j_SetExitMenuFlag_10 = -391,
    j_SetExitMenuFlag_11 = -392,
    j_SetExitMenuFlag_14 = -393,
    jmpSetExitMenuFlag = -394,
    jmp_SetExitMenuFlag = -395,
    jmp_SetExitMenuFlag_2 = -396,
    jmp_SetExitMenuFlag_3 = -397,
    jmp_SetExitMenuFlag_4 = -398,
    jmp_SetExitMenuFlag_5 = -399,
    jmp_SetExitMenuFlag_6 = -400,
    jmp_SetExitMenuFlag_7 = -401,
    jmp_SetExitMenuFlag_8 = -402,
    jmp_SetExitMenuFlag_9 = -403,
    nullsub_18 = -404,
    nullsub_19 = -405,
    nullsub_21 = -406,
    nullsub_25 = -407,
    nullsub_9 = -408,
};

extern Register eax, ebx, ecx, edx, esi, edi, ebp, tmp;
extern Flags flags;
extern int32_t stack[1024];
extern int32_t stackTop;

extern uint16_t * const g_memWord;
extern uint32_t * const g_memDword;
extern SwosVariables * const vars;
#define swos (*SwosVM::vars)

#ifndef sizeofarray
# define sizeofarray(a) (sizeof(a) / sizeof((a)[0]))
#endif

uint32_t readMemory(uint32_t addr, int size);
void writeMemory(uint32_t addr, int size, uint32_t value);
char *offsetToPtr(uint32_t offset);
char *getExtraMemoryArea();
SwosDataPointer<char> allocateMemory(size_t size);
SwosDataPointer<char> allocateString(const char *str);
SwosDataPointer<char> cacheString(const char *str);
void resetStringCache(uint32_t mark);
void releaseMemory(uint32_t mark);
uint32_t getMemoryMark();
uint32_t registerPointer(const void *ptr);
uint32_t getPointerPoolMark();
void releasePointers(int mark);

using VoidFunction = void (*)();
VoidFunction fetchProc(int index);
void invokeProc(int index);
int registerProc(VoidFunction proc);
uint32_t getProcMark();
void releaseProcs(uint32_t mark);

using MemoryMark = std::tuple<uint32_t, uint32_t, uint32_t, uint32_t>;
MemoryMark markAllMemory();
void releaseAllMemory(const MemoryMark& mark);
bool isExternalPointer(uint32_t addr);

#ifdef DEBUG
# ifndef debugBreak
void debugBreak();
# endif
void initSafeMemoryAreas();
void verifySafeMemoryAreas();
#else
# ifndef debugBreak
#  define debugBreak()
# endif
static inline void initSafeMemoryAreas() {}
static inline void verifySafeMemoryAreas() {}
#endif

# define push(a) (stack[--stackTop] = (a))
# define pop(a) ((a) = stack[stackTop++])

static uint16_t& ax = eax.lo16;
static uint16_t& bx = ebx.lo16;
static uint16_t& cx = ecx.lo16;
static uint16_t& dx = edx.lo16;
static uint16_t& si = esi.lo16;
static uint16_t& di = edi.lo16;
static uint16_t& bp = ebp.lo16;
static uint8_t& ah = eax.hi8;
static uint8_t& al = eax.lo8;
static uint8_t& bh = ebx.hi8;
static uint8_t& bl = ebx.lo8;
static uint8_t& ch = ecx.hi8;
static uint8_t& cl = ecx.lo8;
static uint8_t& dh = edx.hi8;
static uint8_t& dl = edx.lo8;

inline bool isSwosPtr(const void *inPtr) {
    auto ptr = reinterpret_cast<const uint8_t *>(inPtr);
    return ptr >= g_memByte + kSafeMemAreaSize && ptr + 4 <= g_memByte + kMemSize - kSafeMemAreaSize;
}

inline uint32_t ptrToOffset(const void *ptr) {
    assert(!ptr || ptr == kSentinel || isSwosPtr(ptr));

    if (!ptr)
        return 0;

    if (ptr == kSentinel)
        return -1;

    return reinterpret_cast<const uint8_t *>(ptr) - g_memByte;
}

}
